services:
  - type: web
    name: blog-app-backend
    env: node
    region: frankfurt
    buildCommand: |
      cd backend &&
      mkdir -p public/uploads &&
      cp -r models routes middleware server.js package.json package-lock.json ./ &&
      npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
    runtime: node
    nodeVersion: 18

  - type: web
    name: blog-app-frontend
    env: node
    region: frankfurt
    buildCommand: |
      cd frontend &&
      npm install &&
      npm install -D tailwindcss@latest postcss@latest autoprefixer@latest &&
      npx tailwindcss init -p &&
      npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        sync: false
    runtime: node
    nodeVersion: 18 