services:
  - type: web
    name: blog-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8080
    healthCheckPath: /api/health

  - type: web
    name: blog-frontend
    env: node
    region: singapore
    plan: free
    buildCommand: cd frontend && npm install --production=false && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://blog-app-backend-qy4q.onrender.com
    healthCheckPath: /api/health
    buildFilter:
      paths:
        - frontend/**/*.*
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 