services:
  - type: web
    name: blog-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        value: https://blog-app-mern-frontend-bfu0.onrender.com
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    healthCheckPath: /health

  - type: web
    name: blog-frontend
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://blog-app-backend-qy4q.onrender.com
      - key: API_URL
        value: https://blog-app-backend-qy4q.onrender.com
    healthCheckPath: /health
    buildFilter:
      paths:
        - frontend/**/*.* 